Description: CloudFormation template for MultiOrg POC with Secrets and Lambda function

Parameters:
  CallCenterApiName:
    Type: String
    Description: Name of the Call Center API

  ConnectInstanceId:
    Type: String
    Description: Amazon Connect Instance ID

  SalesforceOrgId:
    Type: String
    Description: Salesforce Organization ID

  MpaId:
    Type: String
    Description: The AWS Account ID of the Management and Provisioning Account (MPA)

  S3BucketForScvResources:
    Type: String
    Description: The S3 bucket that stores SCV resources, like Lambda functions

  S3BucketForTenantResources:
    Type: String
    Description: The S3 bucket that stores resources for the tenant, like voice recordings and transcripts.

  OrgDomainName:
    Type: String
    Description: Salesforce Org Domain Name

  Scrt2MyDomainUrl:
    Type: String
    Description: SCRT2 MyDomain URL

  LightningDomainUrl:
    Type: String
    Description: Lightning Domain URL for approved origins

  SalesforceRelease:
    Type: String
    Description: Salesforce Major Release Version
    Default: 258.0

  Version:
    Type: String
    Description: Stack Version and Lambda Version
    Default: V19.0

  PermissionBoundaryARN:
    Type: String
    Description: ARN of the permission boundary to apply to created roles
    Default: ""

  SalesforceRestApiAuthPrivateKeyValue:
    Default: salesforce-rest-api-auth-private-key-value
    Type: String
    Description: The value of the SSM parameter used to store the Salesforce REST API auth private key.
  SalesforceRestApiAuthConsumerKeyValue:
    Default: salesforce-rest-api-auth-consumer-key-value
    Type: String
    Description: The value of the SSM parameter used to store the Salesforce REST API auth consumer key.
  SalesforceRestApiAuthAccessTokenKeyValue:
    Default: salesforce-rest-api-auth-access-token-key-value
    Type: String
    Description: The value of the SSM parameter used to store the Salesforce REST API Access token.
  SalesforceRestApiAuthAudienceKeyValue:
    Default: salesforce-rest-api-auth-audience-key-value
    Type: String
    Description: The value of the SSM parameter used to store the Salesforce REST API audience value.

Transform: "AWS::Serverless-2016-10-31"
AWSTemplateFormatVersion: '2010-09-09'

Conditions:
  PermissionBoundaryIsNull:
    !Equals [!Ref PermissionBoundaryARN, '']

Resources:
  AuthKeysSSMUtilFunctionLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs22.x
      Content:
        S3Bucket: !Sub '${S3BucketForScvResources}-${AWS::Region}'
        S3Key: !Sub '${SalesforceRelease}/authKeysSSMUtilFunctionLayer${Version}'
      Description: AuthKeysSSMUtilFunction node modules
      LayerName: AuthKeysSSMUtilFunctionLayer

  AuthKeysSSMUtilFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Sub "${S3BucketForScvResources}-${AWS::Region}"
        Key: !Sub "${SalesforceRelease}/authKeysSSMUtil${Version}"
      Handler: index.handler
      AutoPublishAlias: active
      VersionDescription: !Sub "Service Cloud Voice Lambda Version ${Version}"
      Role: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/SCVSSMLambdaExecutionRole"
      Timeout: 60
      Environment:
        Variables:
          LOG_LEVEL: "info"
          SECRET_NAME: !Sub "${CallCenterApiName}-salesforce-secret"
      Runtime: nodejs22.x
      FunctionName: !Sub "${CallCenterApiName}-AuthKeysSSMUtilFunction"
      Layers:
        - Ref: AuthKeysSSMUtilFunctionLayer
      Description: It Creates the Private key in Param store and returns Public SSM key pair which is used for generating the JWT token for invokeTelephonyIntegrationApiFunction Lambda for authenticating to SCRT service.

  MyDomainApprovedOriginAssociation:
    Type: AWS::Connect::ApprovedOrigin
    Properties:
      InstanceId: !Sub "arn:${AWS::Partition}:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}"
      Origin: !Sub "${OrgDomainName}"

  LightningDomainApprovedOriginAssociation:
    Type: AWS::Connect::ApprovedOrigin
    Properties:
      InstanceId: !Sub "arn:${AWS::Partition}:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}"
      Origin: !Sub "${LightningDomainUrl}"

  ConnectSSORoleResource:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        !If [PermissionBoundaryIsNull, !Ref "AWS::NoValue", !Ref PermissionBoundaryARN]
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRoleWithSAML"
            Effect: "Allow"
            Condition:
              StringEquals:
                "saml:aud": https://signin.aws.amazon.com/saml
            Principal:
              Federated: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:saml-provider/SalesforceServiceVoiceIdp_${SalesforceOrgId}"
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action: "connect:GetFederationToken"
                Effect: "Allow"
                Resource:
                  - !Sub "arn:${AWS::Partition}:connect:*:${AWS::AccountId}:instance/${ConnectInstanceId}/user/${!aws:userid}"
                Sid: "ConnectSSOPolicySid"
            Version: "2012-10-17"
          PolicyName: !Sub "${CallCenterApiName}-SAMLPolicy"
      RoleName: !Sub "${CallCenterApiName}-SAMLRole"

  ConnectCallRoleResource:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        !If [PermissionBoundaryIsNull, !Ref "AWS::NoValue", !Ref PermissionBoundaryARN]
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              AWS:
                !Join
                - ""
                - - "arn:"
                  - !Ref "AWS::Partition"
                  - ":iam::"
                  - !Ref MpaId
                  - ":root"
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - "connect:SuspendContactRecording"
                  - "connect:ResumeContactRecording"
                Effect: "Allow"
                Resource: !Sub "arn:${AWS::Partition}:connect:*:${AWS::AccountId}:instance/${ConnectInstanceId}/contact/*"
                Sid: "ConnectCallRoleSid"
            Version: "2012-10-17"
          PolicyName: !Sub "${CallCenterApiName}-ConnectCallPoly"
      RoleName: !Sub "${CallCenterApiName}-ConnectCallRole"

  SCVS3RoleResource:
    Type: "AWS::IAM::Role"
    Properties:
      PermissionsBoundary:
        !If [PermissionBoundaryIsNull, !Ref "AWS::NoValue", !Ref PermissionBoundaryARN]
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              AWS:
                !Join
                - ""
                - - "arn:"
                  - !Ref "AWS::Partition"
                  - ":iam::"
                  - !Ref MpaId
                  - ":root"
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - "kms:Decrypt"
                Effect: "Allow"
                Resource: '*'
              - Action:
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Effect: "Allow"
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${S3BucketForTenantResources}-${AWS::AccountId}/*'
                  - !Sub 'arn:${AWS::Partition}:s3:::${S3BucketForTenantResources}replica-${AWS::AccountId}/*'
                Sid: !Sub "${CallCenterApiName}SCVS3Sid"
            Version: "2012-10-17"
          PolicyName: !Sub "${CallCenterApiName}-SCVS3Policy"
      RoleName: !Sub "${CallCenterApiName}-SCVS3Role"
      MaxSessionDuration: 14400

  SecretManagerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${S3BucketForScvResources}-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/${SalesforceRelease}/SecretManagerStack${Version}.yaml"
      Parameters:
        CallCenterApiName: !Ref CallCenterApiName
        SalesforceOrgId: !Ref SalesforceOrgId
        OrgDomainName: !Ref OrgDomainName
        Scrt2MyDomainUrl: !Ref Scrt2MyDomainUrl
        # The following parameters should be added to Parameters section if not present
        SalesforceRestApiAuthPrivateKeyValue: !Ref SalesforceRestApiAuthPrivateKeyValue
        SalesforceRestApiAuthConsumerKeyValue: !Ref SalesforceRestApiAuthConsumerKeyValue
        SalesforceRestApiAuthAccessTokenKeyValue: !Ref SalesforceRestApiAuthAccessTokenKeyValue
        SalesforceRestApiAuthAudienceKeyValue: !Ref SalesforceRestApiAuthAudienceKeyValue
        SalesforceRestApiAuthSubjectKeyValue: "salesforce-rest-api-auth-subject"
        PermissionBoundaryARN: !Ref PermissionBoundaryARN
        SalesforceRelease: !Ref SalesforceRelease
        Version: !Ref Version

Outputs:
  AuthKeysSSMUtilFunctionArn:
    Description: ARN of the AuthKeysSSMUtil Lambda function
    Value: !GetAtt AuthKeysSSMUtilFunction.Arn

  ConnectSSORoleResource:
    Description: Arn of the role used in the Connect SSO
    Value: !GetAtt ConnectSSORoleResource.Arn

  ConnectCallRoleResource:
    Description: Arn of the role used in the Connect Call Suspend/Resume recording
    Value: !GetAtt ConnectCallRoleResource.Arn